### ISSUE TITLE
Update actions/upload-pages-artifact to v3 in helm-release workflow

### ISSUE THREAD

**Issue by nkbud** [nkbud/terraboard#11]
### Problem
The `.github/workflows/helm-release.yml` workflow currently uses the deprecated `actions/upload-pages-artifact@v2` action. According to the logs and the deprecation notice, `v2` has been deprecated as of April 2024.

### Solution
Update the workflow to use `actions/upload-pages-artifact@v3` instead of `v2`.

### Code Fix
Update the relevant step in `.github/workflows/helm-release.yml` as follows:

```yaml
- name: Upload artifact
  uses: actions/upload-pages-artifact@v3
  with:
    path: './chart-repo'
```

### Steps to Implement
1. Open `.github/workflows/helm-release.yml`.
2. Find the step with `- name: Upload artifact`.
3. Change `uses: actions/upload-pages-artifact@v2` to `uses: actions/upload-pages-artifact@v3`.
4. Commit and push your changes.

This will resolve the deprecation warning and ensure compatibility with the current version of the GitHub Action.
