### ISSUE TITLE
Add Kubernetes Dex login support to access the UI

### ISSUE THREAD

**Issue by nkbud** [nkbud/terraboard#24]
### Feature Request

**Goal:**
- Integrate Kubernetes Dex authentication into the Vue3 application for accessing the UI using OpenID Connect (OIDC).
- Add a login screen to the Vue3 frontend that authenticates users via the configured Dex server.

**Dex Reference:**
- https://dexidp.io/docs/
- Dex is an OIDC identity and OAuth 2.0 provider with pluggable connectors.

**Provided Dex Config Examples:**
```
issuer: https://nisccoop.okta.com
redirectURI: https://kubedex.cicd.nisc.cloud/callback

issuer: https://kubedex.cicd.nisc.cloud
oauth2:
  skipApprovalScreen: true
staticClients:
  - id: airflow-dev
    name: airflow-dev
    redirectURIs:
      - https://airflow-dev.cicd.nisc.cloud/oauth-authorized/okta
```

---

### Tasks for Vue3 Application
1. Implement a login screen that redirects users to the Dex login page.
2. Handle the OIDC authentication flow, including receiving the authorization code and exchanging it for tokens.
3. Store and use the received tokens to authorize API/UI access.
4. Provide clear error handling and logout functionality.
5. Make the Dex issuer URL and redirect URI configurable (via env vars or config file).

---

### Instructions for Dex Server Configuration (Kubernetes)
- Ensure the Dex server has a static client entry for the Vue3 application's redirect URI. For example:

```
issuer: https://kubedex.cicd.nisc.cloud
...
staticClients:
  - id: terraboard-ui
    name: Terraboard UI
    redirectURIs:
      - https://your-terraboard-ui-url/callback
```

- Set `oauth2.skipApprovalScreen: true` if you want to skip the user approval prompt.
- Update the redirect URI to match the callback endpoint of your deployed Vue3 application.
- (Optional) Configure additional connectors or user sources as needed by your organization.

---

**References:**
- [Dex Documentation](https://dexidp.io/docs/)

---

**Acceptance Criteria:**
- Vue3 application has a working OIDC login screen using Dex.
- Documentation provided for required Dex server configuration changes.
- Users can log in and out using Dex from the Terraboard UI.
