### ISSUE TITLE
Build and publish Docker image to GHCR on semver tag push

### ISSUE THREAD

**Issue by nkbud** [nkbud/terraboard#6]
Create a GitHub Actions workflow (publish-to-ghcr.yml) that builds and pushes the Dockerfile in the root directory to GitHub Container Registry (GHCR) on every semver tag push (e.g. v1.2.3). The workflow should:

- Trigger on every push of a semver tag (v*.*.*)
- Build the Docker image using the root Dockerfile
- Tag the image with both the version (e.g., v1.2.3) and 'latest'
- Push the image to ghcr.io/<org>/<repo> (where org and repo are from the repository context)
- Use the official docker build and login actions

Example workflow steps:
- Checkout code
- Set up QEMU and Buildx for multi-architecture builds
- Log in to ghcr.io using GITHUB_TOKEN
- Build and push image with correct tags for both version and latest
- Platforms: linux/amd64,linux/arm64

See below for an example workflow structure:

```yaml
name: Build & Publish to GHCR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          platforms: linux/amd64,linux/arm64
```

This will ensure images are built and published to GHCR on every semver tag and are available with both version and latest tags.
