### ISSUE TITLE
Support IRSA: Allow Helm ServiceAccount Annotations & Default AWS Credential Chain

### ISSUE THREAD

**Issue by nkbud** [nkbud/terraboard#8]
## Helm Templates: Allow Service Account Annotation for IRSA

Update the Helm templates so that the service account allows custom annotations via `values.yaml`. This is needed to support IRSA (IAM Roles for Service Accounts) by allowing users to specify an annotation like:

```yaml
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role
```

**Proposed template change:**
```yaml
metadata:
  ...
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
```

---

## Go AWS Client: IRSA & Default Credentials Chain

Currently, the AWS code requires either static credentials or an explicit role ARN. If neither is provided, it fails with a fatal error. This does not support the AWS Default Credentials Provider Chain, which is necessary for IRSA to work with EKS service account tokens.

Use the aws default credential provider chain, which is available in some version of the aws sdk client libraries. Make sure you're on that version.

---

### Summary
- Update Helm ServiceAccount template to allow arbitrary annotations via values
- Ensure Go AWS code to support IRSA and the AWS default credentials chain

This will allow running `terraboard` in EKS with IRSA and no static AWS credentials.
